/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id("io.freefair.lombok") version "8.0.1" apply false
}

allprojects {
    group = "com.yeti.hexarch.usermgmt"
    version = "0.0.1.SHAPSHOT"

    tasks.withType<JavaCompile> {
        sourceCompatibility = "1.8"
        targetCompatibility = "1.8"
    }
}

subprojects {
    repositories {
        mavenCentral()
    }

    apply {
        // plugins
        plugin("io.freefair.lombok")
    }
}


