version: '3.9'

services:
  mongo:
    container_name: mongo
    image: mongo:6.0.4-focal
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: always
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - secure-network
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL= mongodb://root:password@mongo:27017/
    networks:
      - secure-network
    depends_on:
      - mongo
      
networks:
  secure-network:
    driver: bridge
